[workspace]
members = ["funnel-web", "funnel-shared"]

resolver = "2"

[workspace.dependencies]
funnel-shared = { path = "funnel-shared" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

[profile.release]
opt-level = 2 # fast and small wasm
