[workspace]
members = ["funnel-shared", "funnel-web"]

resolver = "2"

[workspace.dependencies]
funnel-shared = { path = "funnel-shared" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[profile.release]
opt-level = 2
