[package]
name = "funnel-web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "funnel-web"
path = "src/main.rs"

[dependencies]
chrono = "0.4.39"
eframe = { version = "0.30.0", default-features = false, features = [
    "default_fonts",
    "glow",
] }
egui-dropdown = "0.12.0"
egui-selectable-table = "0.1.2"
egui-theme-lerp = "0.1.4"
egui_extras = { version = "0.30.0", features = [
    "datepicker",
    "all_loaders",
    "serde",
] }
egui_plot = "0.30.0"
ehttp = "0.5.0"
ewebsock = "0.8.0"
funnel-shared = { workspace = true }
image = "0.25.5"
log = "0.4.22"
serde = { workspace = true }
serde_json = { workspace = true }
strum = "0.26.3"
strum_macros = "0.26.4"
wasm-bindgen-futures = "0.4.49"
web-sys = "0.3.76"
