[package]
name = "funnel-web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "funnel-web"
path = "src/main.rs"

[[bin]]
name = "dummy_worker"
path = "src/dummy_worker.rs"

[dependencies]
serde = { workspace = true }
funnel-shared = { workspace = true }
ewebsock = "0.6.0"
reqwest = "0.12.7"
serde_json = { workspace = true }
eframe = { version = "0.29.0", default-features = false, features = [
    "default_fonts",
    "glow",
    "persistence",
] }
log = "0.4.22"
wasm-bindgen-futures = "0.4.43"
web-sys = "0.3.70"
egui-dropdown = "0.11.0"
egui_extras = { version = "0.29.0", features = [
    "datepicker",
    "all_loaders",
    "serde",
] }
egui_plot = "0.29.0"
chrono = "0.4.38"
image = "0.25.2"
strum = "0.26.3"
strum_macros = "0.26.4"
gloo-worker = "0.5.0"
egui-theme-lerp = "0.1.2"
